### ISSUE TITLE
User id is not parsed to be URL safe

### ISSUE THREAD

**Issue by SimonIlic** [felix-hilden/tekore#266] opened 2021-12-26 21:42 UTC
### Issue
User id is not parsed to be URL safe. If a valid spotify user id contains a hashtag this results in a bad request to the API leading to 404: Service not found error.

### Expected behavior
Spotify user id's can contain special (url-unsafe) characters. Most importantly for this example: User id's can start with a `#`. These characters should be properly escaped before making requests.

### Steps to reproduce
```python
user_id = '#validuserid'
spotify.playlists(user_id)
```

**Comment by felix-hilden** [comment] 2021-12-26 23:03
Thanks for reporting! The Web API docs don't specify anything about user ID contents, so I'd like to test this myself. Could you provide a concrete user (or multiple) that has a hash or any other problem characters in their ID? We probably won't include them in our test suite, but would be nice to know. Also, I was under the impression that parameters are URL encoded by the underlying HTTP engine. But this might be remnants of `requests` vs our current `HTTPX`, or entirely something I made up. This is more for me to verify personally.

**Comment by SimonIlic** [comment] 2021-12-27 09:13
Hi Felix, thanks for your fast reply. My guess is that `HTTPX` blindly follows whatever URL you give it. I tried to find some random concrete user's for you to play around with: [#test](https://open.spotify.com/user/%23test), [#123](https://open.spotify.com/user/%23123) and [#user](https://open.spotify.com/user/%23user) are all valid users.

**Comment by felix-hilden** [comment] 2021-12-27 09:18
Thanks for the examples, verified, and I'll start working on it!

**Comment by felix-hilden** [comment] 2021-12-27 09:42
Okay, it seems that the problem isn't in URL encoding *per se*. Parameters are correctly encoded, but I suspect that the hash specifically is causing problems, when it is used as an HTML id.. reference.. thingy. `For instance, user ID [`a#`](https://open.spotify.com/user/a#) works unencoded.

Testing on httpbin,[ `/:test`](https://httpbin.org/anything/:test) works, while [`/#test`](https://httpbin.org/anything/#test) returns 404. [Encoding the hash](https://httpbin.org/anything/%23test) succeeds as expected.

So right now I'm leaning towards a special case fix: encoding only the first character if it's a hash. Not that it would be much of a performance benefit to avoid encoding URLs everywhere, but more for simplicity. But I must ask: does this seem reasonable? And have you encountered any other types of invalid user IDs, or the same problem in other parts of the API?

**Comment by felix-hilden** [comment] 2021-12-27 10:07
The behavior from the API is somewhat inconsistent though. Fetching `s.user("a%23a")` returns an encoded URI, but a decoded user ID. I wonder if this is something they'd like to have a look at, so I posted a [topic](https://community.spotify.com/t5/Spotify-for-Developers/Inconsistencies-with-resources-that-have-hashes-like-user-ID-a-a/m-p/5320411#M3841) on the Spotify Dev forum. Hopefully they'll answer!

**Comment by SimonIlic** [comment] 2021-12-27 11:44
Very interesting! I have only encountered this with usernames, but a similar behaviour can be expected with categories (as you describe in your topic on the Spotify Dev forum) or anywhere with any other resource where the ID can be something more then just a UUID generated by Spotify. For now user ID and category ID seem to be [the only two](https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids). Honestly it surprised me that Spotify allows # in usernames. Just seems like such a headache as evidenced by this bug report.

Your proposed fix seems reasonable to me, although the API might expand in the future, allowing more IDs to contain '#'. Perhaps it's best to safely escape '#' out of all Spotify IDs?

**Comment by felix-hilden** [comment] 2021-12-27 11:52
Oh you're right, that page does enumerate all of the different ID types 👍 I wouldn't worry about generic Spotify IDs though as they are base-62, which does not include any special characters. But yeah, I've also wondered why the user ID is essentially the user name, rather than some generated ID. But oh well 😄

I think we'll wait a bit for Spotify to respond, hopefully within a week or so, and depending on the response I'll apply the appropriate fix. Given that categories are managed by Spotify I wouldn't expect hashes to be a problem there, so I'm still convinced that special casing user IDs is the way to go. We'll see!

**Comment by SimonIlic** [comment] 2021-12-27 12:41
Great! I guess we'll see in the near future.
Thanks and have a nice day! :)

**Comment by SimonIlic** [comment] 2022-01-13 15:10
Fair of you to let them know. Good luck with the fix

**Comment by felix-hilden** [comment] 2022-01-14 08:54
This has some broader implications on our ID-URI conversion as well. Currently we don't recognise `user` as a valid URI type, but it definitely is. And because of that, we can't assume them to be base-62 anymore even though the documentation says so. So we might have to change some logic there too.

**Comment by felix-hilden** [comment] 2022-01-15 23:22
So as the commit stands, we'll also escape hashes in user IDs for URL conversion, just for consistency. I'll close this issue when the tests pass, and if nothing else comes up, there will be a new minor release soon!

**Closed** 2022-01-15 23:25 UTC
Labels: bug
